#!/usr/bin/env python3
"""
扫指定目录的代码文件，抓驼峰命名 + 全大写缩写，按频率排序输出。
输出格式：一行一词，可直接喂 MK CorrectionDictionary 的 .txt 加载器。

Usage:
    scan-codebase.py [--top N] [--min-freq N] [--out FILE] DIR1 [DIR2...]

    无 --out 写到 stdout；典型用法：
    ./scan-codebase.py --out ~/.we/correction-dictionary-codebase.txt \\
                        ~/Desktop/my-code ~/Desktop/cmm
"""
import os, sys, re, argparse
from collections import Counter
from datetime import datetime

EXTS = {'.swift', '.ts', '.tsx', '.py', '.rs'}
EXCLUDES = {
    'node_modules', '.git', '.build', '.next', '.cache', '.venv',
    'dist', 'build', 'out', 'target', '__pycache__', 'venv',
    'coverage', '.turbo', '.parcel-cache', 'tmp',
}
# 驼峰 ≥2 个大写字母 ｜ 全大写缩写 3-6 字母
PATTERN = re.compile(r'\b([A-Z][a-zA-Z]*[A-Z][a-zA-Z]+|[A-Z]{3,6})\b')
MAX_FILE_SIZE = 1024 * 1024  # 1MB / 文件


def scan(roots):
    counter = Counter()
    files_scanned = 0
    for root in roots:
        root = os.path.expanduser(root)
        if not os.path.isdir(root):
            print(f"warn: {root} not a directory, skip", file=sys.stderr)
            continue
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = [d for d in dirnames if d not in EXCLUDES and not d.startswith('.git')]
            for fn in filenames:
                ext = os.path.splitext(fn)[1].lower()
                if ext not in EXTS:
                    continue
                path = os.path.join(dirpath, fn)
                try:
                    if os.path.getsize(path) > MAX_FILE_SIZE:
                        continue
                    with open(path, 'r', encoding='utf-8', errors='ignore') as f:
                        text = f.read()
                    counter.update(PATTERN.findall(text))
                    files_scanned += 1
                except Exception:
                    continue
    return counter, files_scanned


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('roots', nargs='+', help='Root directories to scan')
    ap.add_argument('--top', type=int, default=300, help='Take top-N by frequency (default: 300)')
    ap.add_argument('--min-freq', type=int, default=3, help='Minimum frequency to include (default: 3)')
    ap.add_argument('--out', type=str, default=None, help='Output file (default: stdout)')
    args = ap.parse_args()

    counter, files = scan(args.roots)
    out_lines = [
        f"# Auto-generated by scan-codebase.py at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"# Roots: {' '.join(args.roots)}",
        f"# Files scanned: {files}; unique tokens: {len(counter)}; output top {args.top} (min freq {args.min_freq})",
        "",
    ]
    kept = 0
    for token, count in counter.most_common(args.top):
        if count < args.min_freq:
            break
        out_lines.append(token)
        kept += 1
    output = "\n".join(out_lines) + "\n"

    if args.out:
        with open(os.path.expanduser(args.out), 'w') as f:
            f.write(output)
        print(f"Wrote {kept} terms to {args.out} (scanned {files} files)", file=sys.stderr)
    else:
        sys.stdout.write(output)
        print(f"\n# {kept} terms output (scanned {files} files)", file=sys.stderr)


if __name__ == '__main__':
    main()
